### ISSUE TITLE
Determine how to supplement ProBiz data (whichgeography, what kind of builders)

### ISSUE THREAD

**Issue by wolske** [annitodd/PhoenixDataRepo#12]
ProBiz includes data for 277 building company firms, which, in total have 1096 offices. (Note however, that a few of these are in Canada). 
Based on our exploration of Probiz data [here ](https://uchicago.box.com/s/n4dad4d7xrjuuz3hektvcfj98sr28tss) (PHX_ProBiz_Builder_summary_table_EXPLORING_COUNTS.xlsx), it seems there are:

- 198 companies that only work in one state (or province?); 79 that work in more than one
- 244 companies that have at least one construction manager; 223 companies that have at least one sales manager

And across all of the companies and all of the offices, we have 5,284 contacts, comprised of:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/wolske/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/wolske/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#0563C1">

Number of corporate leaders |   | 255
-- | -- | --
Number of   division managers |   | 843
Number of   marketing managers |   | 653
Number of   Sales Managers |   | 1136
Number of   construction/bldg managers | |1431
Number of   operations managers |   | 565
Number of   Design managers |   | 278
Number of   architects |   | 123

</body>

</html>

We need to determine how to best supplement these data using Data Axle and/or builder names extracted from LBNL's data.

**Comment by RobBot00** [comment]
Content of issue is not currently relevant.
