### ISSUE TITLE
Fix mapping between ProBiz subsidiaries and state of operation

### ISSUE THREAD

**Issue by RobBot00** [annitodd/PhoenixDataRepo#69]
## Summary
To understand the geographic coverage of our production builders, we'd like combine the geographic information we have from ProBiz and ProBuilder. We do that in 'PHX_CTB_04_Builder_State_mapping.ipynb' however in it's current state, it fails to correctly map the subsidiaries in ProBiz to there appropriate state, which can be see [here](https://uchicago.box.com/s/hp3rkbxcb2u66ag2t5mgl6tlg1aclu4j) ('PHX_CTB_02_Parent_Builders_States.csv'). For example, "Century Complete" is a subsidiary of "Century Communities"; these both exist in ProBiz. However, we have an NA for the `pro_biz` and `state` variable.

**Comment by eshanprashar** [comment]
@RobBot00 : Just noticed this. Wanted to add a clarification hoping it saves some time in resolving the issue:  'PHX_CTB_04_Builder_State_mapping.ipynb' is an old file that should not be used. The latest file with mapping of states is actually _PHX_CTB_01_Prod_Builders_Subsidiaries_States_Mapping.ipynb_ saved in 2. analysis folder. 

I ran this file on branch #41 to replicate this issue and did not encounter the error you mentioned. Please let me know if you need help with anything - I'd be happy to jump on a quick call if that saves time.

**Comment by RobBot00** [comment]
@eshanprashar 
Thanks for these clarifications! Super helpful, I think this still isn't working 100% correctly, though I think it's a simple fix.  Let me explain:

Checkout "A.R.B.C. Corporation" in the "[PHX_CTB_02_Parent_Builders_States.csv"](https://uchicago.box.com/s/hp3rkbxcb2u66ag2t5mgl6tlg1aclu4j) file, currently the `probiz` variable is a "0". But check out "A.R.B.C. Corporation" in the [crosswalk](https://uchicago.box.com/s/nc2rxj8yecpjut38nkv0s1djhfwobc9p), you'll see that it is in ProBiz, but its a subsidiary! So this should be a "1" in "PHX_CTB_02_Parent_Builders_States.csv".  

I think the problem in our current code is that we only compare the name against the `probiz_parent_co_name` variable, when the `probiz` column should be a "1" if you are in `probiz_parent_co_name` or `probiz_subsidiary_co_name`.

Can you prioritize this fix? Let me know if it's feasible to fix this but Monday morning, sorry for the short turn around! Hopefully its quick.

**Comment by eshanprashar** [comment]
@RobBot00 : I've updated the code and csv such that subsidiaries also have a '1' in the probiz column. Also, in the 'probiz_co_name', I've added the name of the parent builder when the 'representative_builder_name' is a subsidiary. The latter column remains unchanged. I've pushed these changes on branch #41. 
Note that this doesn't affect the builder-state mapping at all - that was correct before too. 
Let me know if anything isn't clear!

**Comment by RobBot00** [comment]
Perfect! Thanks Eshan. You can push these directly to main if you wish.

**Comment by RobBot00** [comment]
@eshanprashar Just wanted to double check that this code was pushed? I'll close out this issue if it is :)

**Comment by eshanprashar** [comment]
Hey @RobBot00! I'd pushed these to branch #41. The changes still need to be merged with main.
